name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [11, 17, 19]
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1
      - name: Build with Gradle
        run: |
         chmod +x gradlew
         ./gradlew build --stacktrace
      - name: Archive test results
        if: "${{ always() }}"
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
        with:
          name: "test-results-java${{ matrix.java }}"
          path: |
            build/reports/
            plugins/*/build/reports/
            build/test-results/**/*.xml
  publish-test-results:
    runs-on: ubuntu-22.04
    needs: [build]
    permissions:
      issues: write
      pull-requests: write
      checks: write
    if: success() || failure()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b # v2
        with:
          check_name: Test Results
          files: artifacts/*/build/test-results/**/*.xml
